* user_action.csv：用户行为表
* feed_info.csv：Feed信息表（其中feed表示的是内容流，也就是content feed，一系列按照特定顺序或者基于某种规则展示給用户的内容集合）
* feed_embeddings.csv：Feed向量表
* test_a.csv：A榜测试集
* submit_demo_初赛a.csv：A榜提交结果demo

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Concatenate, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import json
import utils
import importlib
importlib.reload(utils)
from utils import *

## 数据读取

In [57]:
feed_df=pd.read_csv('./data/feed_info.csv')
feed_df.head(3)

,feedid,authorid,videoplayseconds,description,ocr,asr,bgm_song_id,bgm_singer_id,manual_keyword_list,machine_keyword_list,manual_tag_list,machine_tag_list,description_char,ocr_char,asr_char
0,43549,6165,38,104741 122649 8109 117252 65632 23463 118668 4...,139499 59421 82007 142955 27736 83577 52394 11...,142955 27736 83577 103956 32010 34170 89740 90...,19356.0,11703.0,15506;7715;17582,26334;219;25209;7715;18541,81;269;159;6,269 0.8525666;81 0.8525666;8 1.1e-07;306 0.0;2...,26439 5247 6426 3827 1882 26018 20744 22204 30...,25926 8491 13394 2203 26439 6243 33054 16435 1...,2203 26439 6243 33054 16435 16307 17070 24908 ...
1,77432,9386,60,35753 27736 146603 73055 11794 101761 11794 81...,35753 146603 73055 11794 101761 67496 16933 52...,146739 14368 79290 79213 47366 8109 33194 1198...,NaN,NaN,8199;18322;4243,24078;19924,194;267;159;6,267 0.99293476;194 0.99293476,31010 32495 6243 13923 15360 30483 2709 26084 ...,31010 32495 13923 15360 30483 2709 26084 15160...,7259 20851 5061 26207 17573 17531 15117 20072 ...
2,12921,2996,15,114413 107973 117252 27736 41035 32715 125374 ...,NaN,NaN,10288.0,11354.0,NaN,11696;6926,202;23;160;6,23 0.64771646;202 0.64771646,27077 10050 27464 20072 26018 6243 21492 14750...,NaN,NaN

In [58]:
action_df=pd.read_csv('./data/user_action.csv')
action_df.head(3)

,userid,feedid,date_,device,read_comment,comment,like,play,stay,click_avatar,forward,follow,favorite
0,8,71474,1,1,0,0,1,500,5366,0,0,0,0
1,8,73916,1,1,0,0,0,250,1533,0,0,0,0
2,8,50282,1,1,0,0,0,750,1302,0,0,0,0

In [59]:
# 预测数据
test=pd.read_csv('./data/test_a.csv')
test.head(3)

   userid  feedid  device  read_comment  like  click_avatar  forward
0   14298   67227       1           NaN   NaN           NaN      NaN
1   68356   91864       2           NaN   NaN           NaN      NaN
2   49925  104657       2           NaN   NaN           NaN      NaN

In [60]:
# 合并数据
merged_df = pd.merge(action_df, feed_df, on='feedid', how='left')
merged_df.head(3)

,userid,feedid,date_,device,read_comment,comment,like,play,stay,click_avatar,forward,follow,favorite,authorid,videoplayseconds,description,ocr,asr,bgm_song_id,bgm_singer_id,manual_keyword_list,machine_keyword_list,manual_tag_list,machine_tag_list,description_char,ocr_char,asr_char
0,8,71474,1,1,0,0,1,500,5366,0,0,0,0,1528,11,110142 37527 123078 110142 134872 294 146821 2...,50275 5643 42751 120238 83167 1371 93533 89031...,104002 104002 104002 104002 104002 104002 1040...,13745.0,3556.0,NaN,7978;9680,219;6;124,266 0.68073416;41 0.68073416,24513 8512 27464 24513 30027 73 23103 6243 287...,11458 1254 28079 20753 23952 10212 8740 32214 ...,23112 23112 23112 23112 23112 23112 23112 2311...
1,8,73916,1,1,0,0,0,250,1533,0,0,0,0,1442,16,NaN,NaN,117252 44399 22662 4438,NaN,NaN,NaN,4388;24079;19399;19166;22371;5615,308;6,266 0.39245349;261 0.39245349;8 3.8e-07;306 0....,NaN,NaN,26018 10043 30420 969
2,8,50282,1,1,0,0,0,750,1302,0,0,0,0,8648,31,95647 49085 1824 140316 56344 45723 121036 977...,NaN,104002 104002 104002 104002 104002 104002 1040...,NaN,NaN,NaN,5077;17881;5132;25008;61;17812,9;6;222;222,16 0.33405718;332 0.33405718;8 7e-08;306 0.0;2...,21277 21277 1873 3110 32556 22468 20201 12785 ...,NaN,23112 23112 23112 23112 23112 23112 23112 2311...

### 数据基本信息查看

In [24]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7739867 entries, 0 to 7739866
Data columns (total 27 columns):
 #   Column                Dtype
---  ------                -----
 0   userid                int64
 1   feedid                int64
 2   date_                 int64
 3   device                int64
 4   read_comment          float64
 5   comment               float64
 6   like                  float64
 7   play                  float64
 8   stay                  float64
 9   click_avatar          float64
 10  forward               float64
 11  follow                float64
 12  favorite              float64
 13  authorid              int64
 14  videoplayseconds      int64
 15  description           object
 16  ocr                   object
 17  asr                   object
 18  bgm_song_id           float64
 19  bgm_singer_id         float64
 20  manual_keyword_list   object
 21  machine_keyword_list  object
 22  manual_tag_list       object
 23  machine_tag_list      object
 24  description_char      object
 25  ocr_char              object
 26  asr_char              object
dtypes: float64(11), int64(6), object(10)
memory usage: 1.6+ GB

In [52]:
# 分析prediction_df数据集
num_preds, cat_preds = analyze_data(merged_df, "数据集")

==================================================
分析数据集: 数据集
总行数: 7317882
总列数: 27

前5行数据:

,userid,feedid,date_,device,read_comment,comment,like,play,stay,click_avatar,...,asr,bgm_song_id,bgm_singer_id,manual_keyword_list,machine_keyword_list,manual_tag_list,machine_tag_list,description_char,ocr_char,asr_char
0,8,71474,1,1,0,0,1,500,5366,0,...,104002 104002 104002 104002 104002 104002 1040...,13745.0,3556.0,NaN,7978;9680,219;6;124,266 0.68073416;41 0.68073416,24513 8512 27464 24513 30027 73 23103 6243 287...,11458 1254 28079 20753 23952 10212 8740 32214 ...,23112 23112 23112 23112 23112 23112 23112 2311...
1,8,73916,1,1,0,0,0,250,1533,0,...,117252 44399 22662 4438,NaN,NaN,NaN,4388;24079;19399;19166;22371;5615,308;6,266 0.39245349;261 0.39245349;8 3.8e-07;306 0....,NaN,NaN,26018 10043 30420 969
2,8,50282,1,1,0,0,0,750,1302,0,...,104002 104002 104002 104002 104002 104002 1040...,NaN,NaN,NaN,5077;17881;5132;25008;61;17812,9;6;222;222,16 0.33405718;332 0.33405718;8 7e-08;306 0.0;2...,21277 21277 1873 3110 32556 22468 20201 12785 ...,NaN,23112 23112 23112 23112 23112 23112 23112 2311...
3,8,11391,1,1,0,0,1,3750,5191,0,...,142955 80924 45012 25794 16650 8097,13096.0,5012.0,24390;14546;6355,17918;131;22816,228;12;159;6,12 0.867993;228 0.867993;8 6.3e-07;306 0.0;207...,7357 22439 31380 12371 18881 26018 2223 10045 ...,6244 28921 12837 199 30086,2203 26439 17681 17681 10226 8481 3703 1872
4,8,27349,1,1,0,0,0,250,800,0,...,150623 17721 287 66591 4438,22215.0,7899.0,9868;27100;11411,23257;20650;23257;8693;26486;25995;7144;19699,322;13;159;6,266 0.78305119;41 0.78305119;8 0.0;306 0.0;207...,17297 28718 10155 5967 17297 14126 26193 20860...,13519 14749 12 19791 20857 14040 22468 89 8481...,5990 15640 30749 29499 66 4956 7578 969

数据类型统计:
int64      15
object     10
float64     2
Name: count, dtype: int64

数值型特征(numeric_features):
['date_', 'device', 'read_comment', 'comment', 'like', 'click_avatar', 'forward', 'follow', 'favorite', 'videoplayseconds']

类别型特征(categorical_features):
['userid', 'feedid', 'play', 'stay', 'authorid', 'description', 'ocr', 'asr', 'bgm_song_id', 'bgm_singer_id', 'manual_keyword_list', 'machine_keyword_list', 'manual_tag_list', 'machine_tag_list', 'description_char', 'ocr_char', 'asr_char']

数值型特征描述统计:

,count,mean,std,min,25%,50%,75%,max
date_,7317882.0,7.801455,4.063833,1.0,4.0,8.0,11.0,14.0
device,7317882.0,1.765396,0.423751,1.0,2.0,2.0,2.0,2.0
read_comment,7317882.0,0.035016,0.183820,0.0,0.0,0.0,0.0,1.0
comment,7317882.0,0.000405,0.020111,0.0,0.0,0.0,0.0,1.0
like,7317882.0,0.025805,0.158553,0.0,0.0,0.0,0.0,1.0
click_avatar,7317882.0,0.007533,0.086467,0.0,0.0,0.0,0.0,1.0
forward,7317882.0,0.003821,0.061698,0.0,0.0,0.0,0.0,1.0
follow,7317882.0,0.000721,0.026844,0.0,0.0,0.0,0.0,1.0
favorite,7317882.0,0.001342,0.036615,0.0,0.0,0.0,0.0,1.0
videoplayseconds,7317882.0,32.255837,109.232491,2.0,14.0,25.0,53.0,25200.0

类别型特征唯一值统计:

userid:
唯一值数量: 20000
前10个最常见值:
userid
32579     980
9541      974
69134     969
239494    968
246409    964
70684     962
39554     962
114022    961
118651    960
100226    958
Name: count, dtype: int64

feedid:
唯一值数量: 96564
前10个最常见值:
feedid
46022     6841
88646     4442
101297    4419
24381     4310
73903     4304
64025     4255
67305     4077
100591    3889
100065    3821
5662      3745
Name: count, dtype: int64

play:
唯一值数量: 201721
前10个最常见值:
play
0       986828
750      47166
500      28029
1250     27896
1000     26532
1500     26298
2000     22883
1750     22057
2500     19571
2250     17332
Name: count, dtype: int64

stay:
唯一值数量: 220343
前10个最常见值:
stay
0      1077
998     806
996     775
1       772
999     757
997     735
975     725
977     724
976     720
978     719
Name: count, dtype: int64

authorid:
唯一值数量: 18429
前10个最常见值:
authorid
18286    32956
14028    27841
14653    25149
4537     23040
11296    22529
1072     21457
15610    20949
12577    19760
2979     18769
1591     18468
Name: count, dtype: int64

description:
唯一值数量: 90599
前10个最常见值:
description
15350 143050 116167 92696 44517 1181 102431 6994 6994 6994 6994 6994 6994 13997 78065 135737 134885 6994                                                                                                                                                                                                                                                                                                                                                                                                                                                     38360
32374 44517 1181 102431 6994 6994 6994 6994 6994 6994 13997 78065 135737 134885 6994                                                                                                                                                                                                                                                                                                                                                                                                                                                                         14498
15350 143050 116167 92696 44517 1181 102431 6994 6994 6994 6994 6994 6994 13997 75616 17054 61794 6994                                                                                                                                                                                                                                                                                                                                                                                                                                                       10707
32374 44517 48796 116916 102431 6994 6994 6994 6994 6994 102431 102431 13997 119707 137824 6994 134820 119707 137824                                                                                                                                                                                                                                                                                                                                                                                                                                          8344
32374 44517 48796 116916 102431 6994 6994 6994 6994 6994 102431 102431 134820 137824 134820 89155 134820 39160 13997 119707 137824                                                                                                                                                                                                                                                                                                                                                                                                                            7303
116419 17353 8109 120740 107673 133296 37630 58124 78844 96099 93533 4438 50005 124449 5070 25290 25019 102431 134820 120740 134820 13794 3574 134820 86686 134820 82083 134820 92327                                                                                                                                                                                                                                                                                                                                                                         6841
134820 129014                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 5368
4430 8108 101640 6994 105363 24054 44854 26564 6470 134913 54700 49085 93563 61533 134913 49085 93563 50059 49085 4431 102431 51819 45312 117347 110142 149596 78029 128335 117252 27736 6470 134913 18149 8109 117252 140147 128335 8109 75222 45312 62197 110142 149596 25917 8109 35873 22023 7473 26295 59731 35669 78844 84789 62436 2776 12240 31279 25794 134820 6470 134913 54700 134820 117960 134820 61533 134913 134820 91453 37731 121712 134820 52495 121712 134820 50059 134820 111660 1052 13794 134820 9852 11442 7340 128800 35669 23396     5086
32374 44517 48796 116916 102431 6994 6994 6994 6994 6994 102431 102431 134820 137824 134820 89155 134820 39160 13997 117388 23623 137824                                                                                                                                                                                                                                                                                                                                                                                                                      4471
5070 83627 1890 89316 128064 27736 49085                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      4442
Name: count, dtype: int64

ocr:
唯一值数量: 69913
前10个最常见值:
ocr
128524 56772 146231 146231 146231 95647 6994 44399 135558 117252 135136 27773 25794 82007 48081 115841 26564 76095 117252 122640 108803 106949 93566 93536 61794 68304 82007 125334 6994 117252 135136 27773 25794 82007 90843 12240 34056 82007 125334 6994 1400 8507 82007 146231 16881 755 146231 146231 28467 93536 20248 82007 139718 26564 85360 82007 12240 135739 82083 105232 65648 136974 3145 93563 120068 25794 82007 9837 146492 147438 27736 80029 40236 27783 82007 117252 12240 132715 102383 120740 25794                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     6841
39652 106482                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   4442
127628 56989 43643 88513 43356 93533 145343 90270 27736 110142 112980 113351 107063 90302 27196 56344 69875 19267 122650 129236 101369 82007 88513 43356 93533 145343 90270 27736 110142 112980 113351 107063 90302 27196 56344 69875 19267 122650 15360 82007 88513 43356 93533 145343 90270 27736 110142 112980 113351 107063 90302 27196 56344 69875 19267 122650 15360 82007 99656 89921 43643 88513 43356 93533 145343 90270 27736 110142 112980 113351 107063 90302 27196 56344 69875 19267 122650 15360 82007 84075 89966 43643 88513 43356 93533 145343 90270 27736 110142 112980 113351 107063 90302 27196 56344 69875 19267 122650 15360                                                                                                                                                                                                                                                                                                                                                                                             4310
24004 47551 8109 117252 90302 65612 25794 13665 124090 8109 99614 22091 34198 17349 117252 112478 84616 122222 123671 45012 26564 130814 97364 53706 123671 142973 8109 118750 22535 34198 89287 117252 25794 8109 31395 117252 122640 26564 88810 28180 8109 26564 100406 25794 26564 88810 8109 107652 113003 117252 65632 45012 26564 123681 12214 79303 93569 25794 8109 117252 65632 90302 54491 8109 94170 26564 99614 68588 78557 755 82007 142973 8109 118750 22535 34198 89287 117252 25794 8109 31395 117252 122640 26564 88810 28180 8109 26564 100406 25794 26564 88810 8109 107652 113003 117252 65632 45012 26564 123671 12214 79303 93569 25794 8109 117252 65632 90302 54491 8109 94170 26564 99614 68588 78557 755 117252 117252 102383 25794 8109 112377 755 22535 23659 117252 2336 8109 117252 65632 93563 148254 755                                                                                                                                                                                                      4304
43629 73496 44390 91471 39722 54606 112151 8109 85031 8109 134878 40009 4431 82007 117252 77895 26564 37114 26564 62436 25794 22675 122222 82007 53411 7659 112151 8109 85031 8109 140623 134878 136216 39315 89997 4431 82007 101407 22105 96324 11344 8109 37482 8109 140205 134878 40009 51259 10877 28468 4430 56960 119432 4431 80029 44549 7446 79213 62436 82007 101407 116504 59731 112151 8109 37482 8109 140623 134878 53585 51259 75005 34169 82007 7046 108156 134911 16877 4431 26564 16933 117252 37114 56344 79213 5070 117252 62436 44549 82007 43629 123130 91471 20248 755 117290 96329 69145 8109 85031 8109 150852 65625 755 130818 130818 4430 95343 4431 82007 43629 73496 44390 91471 99187 755 119868 95437 50707 4430 80029 16643 95815 27736 31877 117252 16933 26564 63873 82007 148375 101112 26564 142475 134875 37520 25794 95432 22675 122222 82007 22591 123130 91471 106246 117252 112235 62436 117252 112235 12240 106949 62436 11819 62436 82007 43629 73496 44390 91471 130818 130818 69778 4431 106246    4255
44971 23370 93521 37506 112178 78844 45017 26564 98839 22675 82007 121444 12220 93521 6994 128815 69153 26564 8420 22675 82007 28486 117252 93563 8420 84296 117252 93563 36794 82007 26564 44517 44399 84541 26564 5070 27736 82007 93563 98839 93563 8420 82007 93563 36794 27736 125334 20151 82007 107673 32717 110690 28682 25794 82007 26564 106949 122640 9844 117050 22662 82007 90077 44399 112151 12885 288 27736 143011 82007 26564 112151 62219 56242 44775 27736 82007 117252 112151 136216 56242 82007 136216 56242 106481 124438 25794 82007 118239 26564 10930 90843 82007 128388 82007 89245 146405 117252 93563 128403                                                                                                                                                                                                                                                                                                                                                                                                       3821
51671 68002 27736 117252 66028 25794 103914 47344                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              3745
23607 82007 30488 287 110142 93536 127890 82007 131964 69347 27736 37527 107673 45443 73469 82007 84541 26564 27736 62150 99614 81780 105870 82007 26564 27736 134287 79290 33482 19019 82007 117252 93563 121435 82007 133643 26564 81780 25794 82007 117252 45012 26564 17956 84616 82007 26564 135136 79213 81780 82007 26564 45012 117252 11018 84616 82007 76762 28682 122222 82007 69875 22662 82007 44517 82007 26564 128335 134875 89322 78738 82007 33680 755 100670 82007 106514 106519 89849 82007 106544 11819 82007 91451 89849 82007 106544 122222                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3642
21836 47551 82007 84818 81200 39211 96337 61796 117763 89307 4433 82007 99614 110079 6389 88805 27736 84818 112594 139719 128351 65640 49521 84252 755 80024 93566 73849 37527 111371 56242 116471 82007 93563 67288 40088 52028 9841 6915 82007 62013 93554 21540 44398 67257 82007 130479 106976 23951 61816 137442 106487 27808 16418 60580 69798 82007 95930 32453 21510 133883 68454                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      3547
124087 59731 26737 93384 78844 9844 149593 25794 106221 117252 43556 56505 28237 25794 148514 27736 137781 60927 49525 110778 82007 124087 59731 2375 29641 117252 43356 141392 32121 45913 65775 44866 13794 93563 145339 62219 45012 16650 44517 82007 125334 52060 9844 27736 93536 67250 28237 25794 12885 45913 65775 44866 13794 93563 145339 62219 45012 16650 44517 82007 85868 75625 109274 117252 37630 112793 93566 25290 110142 93536 7473 64313 27736 45706 82007 106221 117252 135558 9844 141045 25794 43556 56505 27736 128809 93536 67250 82007 60927 49525 110778 71431 118709 37527 115638 26564 8109 117252 12240 71431 67285 44617 26564 82007 117050 25794 79213 127715 14405 89860 113002 118671 109721 12240 32374 45861 9844 27736 43556 56505 82007 117252 27736 93536 65638 50834 9844 56344 73051 25794 45913 65775 44866 79213 37527 115638 117252 82007 20248 122222 20248                                                                                                                                       3537
Name: count, dtype: int64

asr:
唯一值数量: 65225
前10个最常见值:
asr
104002 4438                                                                                                              156162
26597 4438                                                                                                                24782
104002 4438 104002 4438                                                                                                   20987
27736 4438                                                                                                                19215
104002 104002 104002 104002 104002 4438                                                                                   15118
104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 4438                                         13681
106481 4438                                                                                                               12181
11819 4438                                                                                                                11863
104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 4438                                  11163
104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 104002 49085     10608
Name: count, dtype: int64

bgm_song_id:
唯一值数量: 23270
前10个最常见值:
bgm_song_id
10198.0    24482
14870.0    23277
17321.0    22664
14840.0    20630
12365.0    20593
10018.0    18533
2644.0     17920
20239.0    17755
18665.0    15693
23575.0    11193
Name: count, dtype: int64

bgm_singer_id:
唯一值数量: 16314
前10个最常见值:
bgm_singer_id
11703.0    52612
1121.0     28382
1570.0     28107
12584.0    25658
4154.0     25638
8233.0     23507
14093.0    23277
14336.0    21927
13271.0    20304
14344.0    18522
Name: count, dtype: int64

manual_keyword_list:
唯一值数量: 45104
前10个最常见值:
manual_keyword_list
26617               45955
5454                31133
26617;208           30071
18863               22371
126                 19389
18600               19122
12726;20219;208     17424
13161               17020
20352               16309
13161;1151;20219    12907
Name: count, dtype: int64

machine_keyword_list:
唯一值数量: 51597
前10个最常见值:
machine_keyword_list
17892;18428    128213
18428;17892    126572
16748           76114
1371            34622
19924           33315
17881;5077      30777
1371;18779      27101
18779;1371      23424
13615;26508     22294
6969            20543
Name: count, dtype: int64

manual_tag_list:
唯一值数量: 3172
前10个最常见值:
manual_tag_list
332;16;159;6         530312
9;6                  510069
219;6                440507
170;239;159;169      291163
191;267;159;145;6    287535
98;267;159;6         235606
49;235;159;6         184612
204;235;159;145;6    159878
328;13;159;6         147158
340;235;159;145;6    105727
Name: count, dtype: int64

machine_tag_list:
唯一值数量: 96140
前10个最常见值:
machine_tag_list
235 0.80389971;49 0.80389971;8 0.0;306 0.0;207 0.00595377;10 0.27194595            6841
267 0.72021401;98 0.72021401;8 0.84543014;306 0.0;207 0.06350361;10 0.27008355     4442
16 0.93439817;332 0.93439817;8 0.0;306 0.0;207 0.00077994;10 0.27067801            4419

bgm_singer_id           3674581
bgm_song_id             3674581
manual_keyword_list     2255381
ocr_char                1905399
ocr                     1886890
asr_char                1721179
asr                     1721179
machine_keyword_list     848552
description              219807
description_char         217989
machine_tag_list          28759
manual_tag_list            6707
dtype: int64

In [53]:
num_feeds, cat_feeds = improved_analyze_data(merged_df, "合并数据集")

==================================================
高级分析数据集: 合并数据集

最终数值型特征:
['comment', 'favorite', 'read_comment', 'click_avatar', 'userid', 'like', 'forward', 'feedid', 'stay', 'play', 'follow', 'authorid', 'date_', 'videoplayseconds']

最终类别型特征:
['bgm_song_id', 'ocr_char', 'userid', 'manual_tag_list', 'description', 'bgm_singer_id', 'asr_char', 'device', 'description_char', 'asr', 'manual_keyword_list', 'feedid', 'machine_tag_list', 'authorid', 'machine_keyword_list', 'ocr']

文本特征需要特殊处理:
['description', 'ocr', 'asr', 'manual_keyword_list', 'machine_keyword_list', 'manual_tag_list', 'machine_tag_list']

高缺失值特征:
['ocr', 'asr', 'bgm_song_id', 'bgm_singer_id', 'manual_keyword_list', 'machine_keyword_list', 'ocr_char', 'asr_char']

In [54]:
pd.set_option('display.max_columns', None)
merged_df.head()

,userid,feedid,date_,device,read_comment,comment,like,play,stay,click_avatar,forward,follow,favorite,authorid,videoplayseconds,description,ocr,asr,bgm_song_id,bgm_singer_id,manual_keyword_list,machine_keyword_list,manual_tag_list,machine_tag_list,description_char,ocr_char,asr_char
0,8,71474,1,1,0,0,1,500,5366,0,0,0,0,1528,11,110142 37527 123078 110142 134872 294 146821 2...,50275 5643 42751 120238 83167 1371 93533 89031...,104002 104002 104002 104002 104002 104002 1040...,13745.0,3556.0,NaN,7978;9680,219;6;124,266 0.68073416;41 0.68073416,24513 8512 27464 24513 30027 73 23103 6243 287...,11458 1254 28079 20753 23952 10212 8740 32214 ...,23112 23112 23112 23112 23112 23112 23112 2311...
1,8,73916,1,1,0,0,0,250,1533,0,0,0,0,1442,16,NaN,NaN,117252 44399 22662 4438,NaN,NaN,NaN,4388;24079;19399;19166;22371;5615,308;6,266 0.39245349;261 0.39245349;8 3.8e-07;306 0....,NaN,NaN,26018 10043 30420 969
2,8,50282,1,1,0,0,0,750,1302,0,0,0,0,8648,31,95647 49085 1824 140316 56344 45723 121036 977...,NaN,104002 104002 104002 104002 104002 104002 1040...,NaN,NaN,NaN,5077;17881;5132;25008;61;17812,9;6;222;222,16 0.33405718;332 0.33405718;8 7e-08;306 0.0;2...,21277 21277 1873 3110 32556 22468 20201 12785 ...,NaN,23112 23112 23112 23112 23112 23112 23112 2311...
3,8,11391,1,1,0,0,1,3750,5191,0,0,0,0,11976,6,32715 49575 54606 85056 90843 23031 61533 9356...,27737 129801 37630 755 95811 95811,142955 80924 45012 25794 16650 8097,13096.0,5012.0,24390;14546;6355,17918;131;22816,228;12;159;6,12 0.867993;228 0.867993;8 6.3e-07;306 0.0;207...,7357 22439 31380 12371 18881 26018 2223 10045 ...,6244 28921 12837 199 30086,2203 26439 17681 17681 10226 8481 3703 1872
4,8,27349,1,1,0,0,0,250,800,0,0,0,0,4370,12,117910 44854 26564 51353 117763 57127 134820 1...,3195 65625 79 89307 93563 62197 127203 25794 2...,150623 17721 287 66591 4438,22215.0,7899.0,9868;27100;11411,23257;20650;23257;8693;26486;25995;7144;19699,322;13;159;6,266 0.78305119;41 0.78305119;8 0.0;306 0.0;207...,17297 28718 10155 5967 17297 14126 26193 20860...,13519 14749 12 19791 20857 14040 22468 89 8481...,5990 15640 30749 29499 66 4956 7578 969

### 数据预处理

In [61]:
import os
import copy
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [62]:
# 合并数据
test['date_'] = 15
action_df = pd.concat([action_df,test])

In [63]:
# 标签列
target = ["read_comment",  # 是否查看评论
          "like",  # 是否点赞
          "click_avatar",  # 是否点击头像
          "forward"] # 是否转发
# 稀疏特征
sparse_features = ['userid', 'feedid', 'authorid', 'bgm_song_id', 'bgm_singer_id']
# 变长序列特征
varlen_features = ['manual_tag_list', # 人工标注的分类标签
                   'manual_keyword_list', 'description'] # 机器标注的关键词
# 稠密特征
dense_features = ['videoplayseconds']

In [64]:
# 数据合并
feed_df = feed_df[['feedid', 'authorid', 'videoplayseconds', 'bgm_song_id', 'bgm_singer_id','manual_tag_list','manual_keyword_list', 'description']]
data = action_df.merge(feed_df, how='left',on='feedid') #行为数据拼接，作者id，bgm_song_id

In [65]:
pd.set_option('display.max_columns',None)
data.head()

,userid,feedid,date_,device,read_comment,comment,like,play,stay,click_avatar,forward,follow,favorite,authorid,videoplayseconds,bgm_song_id,bgm_singer_id,manual_tag_list,manual_keyword_list,description
0,8,71474,1,1,0.0,0.0,1.0,500.0,5366.0,0.0,0.0,0.0,0.0,1528,11,13745.0,3556.0,219;6;124,NaN,110142 37527 123078 110142 134872 294 146821 2...
1,8,73916,1,1,0.0,0.0,0.0,250.0,1533.0,0.0,0.0,0.0,0.0,1442,16,NaN,NaN,308;6,NaN,NaN
2,8,50282,1,1,0.0,0.0,0.0,750.0,1302.0,0.0,0.0,0.0,0.0,8648,31,NaN,NaN,9;6;222;222,NaN,95647 49085 1824 140316 56344 45723 121036 977...
3,8,11391,1,1,0.0,0.0,1.0,3750.0,5191.0,0.0,0.0,0.0,0.0,11976,6,13096.0,5012.0,228;12;159;6,24390;14546;6355,32715 49575 54606 85056 90843 23031 61533 9356...
4,8,27349,1,1,0.0,0.0,0.0,250.0,800.0,0.0,0.0,0.0,0.0,4370,12,22215.0,7899.0,322;13;159;6,9868;27100;11411,117910 44854 26564 51353 117763 57127 134820 1...

In [66]:
data = preprocess(data,dense_features) #特征处理
data = data[dense_features+sparse_features+varlen_features+['date_']+target]

In [ ]:

# def split(column):
#     if not isinstance(column,str):
#         return []
#     keys = column.strip().split(';')
#     for key in keys:
#         if key not in key2index:
#             key2index[key] = len(key2index) + 1
#     return list(map(lambda x: key2index[x], keys))

In [69]:
# 变长特征编码
# 处理manual_keyword_list和manual_tag_list变长特征
encoder = {}

def split(column):
    if not isinstance(column,str):
        return []
    keys = column.strip().split(';')
    for key in keys:
        if key not in key2index:
            key2index[key] = len(key2index) + 1
    return list(map(lambda x: key2index[x], keys))


global key2index
for f in ['manual_keyword_list','manual_tag_list']:
    key2index = {}
    f_list = list(map(split, data[f].values))
    f_length = np.array(list(map(len, f_list)))
    max_len = max(f_length)
    print(f'{f} 字段最长的取值序列长度为 {max_len}')
    # Notice : padding=`post`
    data[f] = list(pad_sequences(f_list, maxlen=max_len, padding='post', ))
    encoder[f] = copy.copy(key2index)

manual_keyword_list 字段最长的取值序列长度为 18
manual_tag_list 字段最长的取值序列长度为 11

In [71]:
# 处理description变长特征
encoder_description={}

def split_by_space(column):
    if not isinstance(column,str):
        return []
    keys = column.strip().split(' ')
    for key in keys:
        if key not in key_to_index_description:
            key_to_index_description[key] = len(key_to_index_description) + 1
    return list(map(lambda x: key_to_index_description[x], keys))

global key_to_index_description
for f in ['description']:
    key_to_index_description={}
    f_list = list(map(split_by_space, data[f].values))
    f_length = np.array(list(map(len, f_list)))
    max_len = max(f_length)
    print(f'{f} 字段最长的取值序列长度为 {max_len}')
    # Notice : padding=`post`
    data[f] = list(pad_sequences(f_list, maxlen=max_len, padding='post', ))
    encoder_description[f] = copy.copy(key_to_index_description)

description 字段最长的取值序列长度为 622

In [72]:
data['description']

0          [1, 2, 3, 1, 4, 5, 6, 7, 8, 9, 10, 11, 3, 12, ...
1          [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2          [39, 12, 40, 41, 42, 43, 44, 45, 20, 21, 46, 4...
3          [14, 59, 60, 61, 62, 63, 64, 65, 66, 62, 7, 67...
4          [68, 69, 19, 70, 71, 72, 35, 68, 35, 73, 74, 0...
                                 ...
7739862    [888, 1939, 1940, 798, 647, 1941, 1226, 353, 1...
7739863    [10, 493, 18681, 469, 7, 1549, 3587, 137, 543,...
7739864    [318, 4660, 1473, 30, 2874, 4660, 28, 9, 30, 2...
7739865    [3712, 3934, 137, 325, 13524, 7, 21, 591, 4146...
7739866    [14, 10, 194, 11659, 7, 21, 761, 20, 29, 35, 2...
Name: description, Length: 7739867, dtype: object

In [73]:
# 稀疏特征编码
for featid in sparse_features:
    print(f"编码ID字段：{featid}")
    encoder[featid] = {uid:ucode+1 for ucode,uid in enumerate(data[featid].unique())} 
    data[featid] = data[featid].apply(lambda x: encoder[featid].get(x,0))

编码ID字段：userid
编码ID字段：feedid
编码ID字段：authorid
编码ID字段：bgm_song_id
编码ID字段：bgm_singer_id

In [74]:
print('数据维度：', data.shape)
print('数据字段：', data.columns.tolist())
print('不同的date_取值: ', data['date_'].unique())
# 资源比较少，可以在这里进行数据采样
data = data.sample(frac = 1.0)

数据维度： (7739867, 14)
数据字段： ['videoplayseconds', 'userid', 'feedid', 'authorid', 'bgm_song_id', 'bgm_singer_id', 'manual_tag_list', 'manual_keyword_list', 'description', 'date_', 'read_comment', 'like', 'click_avatar', 'forward']
不同的date_取值:  [ 1  2  3  5  6  7  8 10 11 12 13 14  4  9 15]

In [75]:
# 构建训练集，验证集和测试集
# 第14天样本作为验证集
train = data[data['date_'] < 14].drop(['date_'],axis = 1)
val = data[data['date_'] == 14].drop(['date_'],axis = 1)  
test = data[data['date_'] == 15].drop(['date_'],axis = 1)

In [76]:
import gc
import joblib
# gc.collect()

In [77]:
train.head()

,videoplayseconds,userid,feedid,authorid,bgm_song_id,bgm_singer_id,manual_tag_list,manual_keyword_list,description,read_comment,like,click_avatar,forward
987320,1.583341,2710,1235,776,536,483,"[34, 35, 9, 2, 0, 0, 0, 0, 0, 0, 0]","[241, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...","[756, 5826, 790, 10, 7, 641, 65, 5827, 0, 0, 0...",0.0,0.0,0.0,0.0
2759866,1.310506,7563,939,615,2,2,"[54, 55, 9, 48, 33, 2, 0, 0, 0, 0, 0]","[729, 730, 626, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[4416, 20, 4416, 20, 35, 4847, 270, 3758, 0, 0...",1.0,0.0,0.0,0.0
5197712,1.327761,14196,4149,2158,2,2,"[50, 11, 9, 40, 2, 0, 0, 0, 0, 0, 0]","[1967, 88, 356, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[35, 4889, 4890, 1324, 2456, 65, 2141, 2297, 1...",0.0,0.0,0.0,0.0
3883438,1.310506,10592,76182,10283,2,2,"[74, 72, 9, 2, 0, 0, 0, 0, 0, 0, 0]","[17955, 17956, 3271, 0, 0, 0, 0, 0, 0, 0, 0, 0...","[522, 30554, 41694, 5115, 10150, 1503, 365, 15...",1.0,0.0,0.0,0.0
3918187,1.631370,10684,5680,2797,2,2,"[44, 32, 9, 2, 0, 0, 0, 0, 0, 0, 0]","[59, 578, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[7971, 12516, 7, 12517, 21, 3268, 8609, 7, 496...",0.0,0.0,0.0,0.0

In [78]:
joblib.dump(train, './data_and_feature/train.txt')
joblib.dump(val, './data_and_feature/val.txt')
joblib.dump(test, './data_and_feature/test.txt')
joblib.dump(encoder, './data_and_feature/encoder.txt')
joblib.dump(encoder_description, './data_and_feature/encoder_description.txt')

['./data_and_feature/encoder_description.txt']

### 生成embedding_feat_dict

In [82]:
embedding_feat_dict = generate_complete_embedding_config(data, encoder, encoder_description)

In [83]:
embedding_feat_dict

{'dense': ['videoplayseconds'],
 'sparse': {'userid': {'vocab_size': 20001, 'embedding_dim': 6},
  'feedid': {'vocab_size': 99172, 'embedding_dim': 6},
  'authorid': {'vocab_size': 18624, 'embedding_dim': 6},
  'bgm_song_id': {'vocab_size': 23740, 'embedding_dim': 6},
  'bgm_singer_id': {'vocab_size': 16603, 'embedding_dim': 6}},
 'sequence': {'manual_tag_list': {'vocab_size': 350,
   'max_len': 11,
   'embedding_dim': 6},
  'manual_keyword_list': {'vocab_size': 22145,
   'max_len': 18,
   'embedding_dim': 6},
  'description': {'vocab_size': 46489, 'max_len': 622, 'embedding_dim': 6}}}

In [84]:
save_json_file('./config/embedding_feat_dict.json', embedding_feat_dict)

文件保存成功!